# -*- coding: utf-8 -*-
"""Plotter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jgNibDqqyOPpXohHTTOByG12BMd-tT6b
"""

import matplotlib.pyplot as plt
import pandas as pd

# data = pd.read_csv('vgg_training.log')

# data.head()

# plt.plot(data['epoch'],data['acc']*100,label='Training')
# plt.plot(data['epoch'],data['val_acc']*100,'-*', color='orange',label='Validation')
# plt.xlabel('Epochs')
# plt.ylabel('Accuracy')
# plt.legend()
# plt.savefig('VGG16_transfer_learning.pdf',format='pdf')

data = pd.read_csv('lenet5_basic_training.log')
data.head()

plt.plot(data['epoch'],data['acc']*100,label='Training')
plt.plot(data['epoch'],data['val_acc']*100, color='orange',label='Validation')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.xticks(data['epoch'])
plt.legend()
plt.savefig('Lenet_transfer_learning.pdf',format='pdf')

